blank_issues_enabled: false
contact_links:
  - name: "Domande generali"
    url: "https://github.com/orgs/alfalearning/discussions"
    about: "Usa le Discussions per domande generali invece di creare un'Issue."
